<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_16</name>
   <tag></tag>
   <elementGuidId>17c82633-0b46-45d9-9e96-0b0d408ca3f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.k-state-hover > a.k-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b25d6a54-6723-4f2b-af6f-f03498aa9cce']/table/tbody/tr[3]/td[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;16&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>364ef099-fec2-4ebc-b976-f8d221ac867a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>37aa22c9-2adf-4511-b175-159a47d49deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>54743691-1785-438d-9c4c-44b076839c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2bad853d-c552-41a0-a091-a1b13392a534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2025/0/16</value>
      <webElementGuid>db2366a7-2091-474d-83b7-b8db5f4076b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>16 Januari 2025</value>
      <webElementGuid>e1d01374-89f2-4169-8328-d4754926f1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>347d8f13-ff92-45ba-a358-f4d85812079a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b25d6a54-6723-4f2b-af6f-f03498aa9cce&quot;)/table[@class=&quot;k-content&quot;]/tbody[1]/tr[3]/td[@class=&quot;k-state-hover&quot;]/a[@class=&quot;k-link&quot;]</value>
      <webElementGuid>3a367a33-655b-4b4c-bc36-922da024b896</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b25d6a54-6723-4f2b-af6f-f03498aa9cce']/table/tbody/tr[3]/td[4]/a</value>
      <webElementGuid>7bceff2c-07c4-429d-ac71-526fa37ba694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'16')]</value>
      <webElementGuid>8284cf23-b923-4f2b-990b-985fc2e83c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/following::a[9]</value>
      <webElementGuid>09f064ab-b6af-4ca8-9bff-459fb40dd6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[3]/following::a[9]</value>
      <webElementGuid>f0e2982c-fa80-4c44-9594-2ec22e621272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::a[9]</value>
      <webElementGuid>55944243-eb74-4d5a-ac3d-7b23a8ab2439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagian Umum - APS'])[1]/preceding::a[9]</value>
      <webElementGuid>0a3f3ebe-3e51-4d4a-9f80-9c659ffadd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16']/parent::*</value>
      <webElementGuid>ea193d66-0a21-472a-9c0f-887d68d40367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[14]</value>
      <webElementGuid>27d42f67-7711-4dd1-95f0-cac940533e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/a</value>
      <webElementGuid>dcf74000-c3a5-4967-ba65-80e5325452c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = '16 Januari 2025' and (text() = '16' or . = '16')]</value>
      <webElementGuid>ad6a43bf-87dd-4508-94ce-7633f3211ea7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
