<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hadir (1)</name>
   <tag></tag>
   <elementGuidId>30d0201b-8a68-413c-85d5-442d3d321124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.k-link.k-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='PanelBar']/li[3]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hadir&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a057a421-357b-4a66-9ed9-0b60d131d710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-state-hover</value>
      <webElementGuid>f309c7aa-a6aa-4f8e-b848-1a8204f75d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Absensi/Form/Hadir</value>
      <webElementGuid>70e23f6f-b940-4b72-b608-d94d39ded771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hadir </value>
      <webElementGuid>a7ecab6c-1545-4442-a758-3dae05a72830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PanelBar&quot;)/li[@class=&quot;k-state-active k-item&quot;]/ul[@class=&quot;k-group k-panel&quot;]/li[@class=&quot;k-state-active k-item&quot;]/a[@class=&quot;k-link k-state-hover&quot;]</value>
      <webElementGuid>d6f90c35-c766-4e08-95ef-658a8c45f532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='PanelBar']/li[3]/ul/li[4]/a</value>
      <webElementGuid>fb54dd1e-e822-403b-90cd-34df61a325f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hadir')]</value>
      <webElementGuid>12c48ad2-7a3f-4d45-b297-84cbc56a1aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketidakhadiran'])[1]/following::a[1]</value>
      <webElementGuid>c46410cf-77c8-41af-ac6e-608a5e9390c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terlambat'])[1]/following::a[2]</value>
      <webElementGuid>0cdd0b1e-f81e-4a05-b54e-6c6b64d8a74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amnesti Absen'])[1]/preceding::a[1]</value>
      <webElementGuid>195aa5fc-a6a1-4e57-bd02-36a6e0b81c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hadir']/parent::*</value>
      <webElementGuid>cc31edc9-29e7-4cd4-b9df-68ab091819df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Absensi/Form/Hadir')]</value>
      <webElementGuid>4850e0e4-77b8-489d-9e9a-09be966b60f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[4]/a</value>
      <webElementGuid>e38da610-8122-486d-8ff9-da7d9a7a9f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Absensi/Form/Hadir' and (text() = 'Hadir ' or . = 'Hadir ')]</value>
      <webElementGuid>4d4f2799-322d-4605-9276-7f7e47c4d955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
