<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>70e61c56-6263-4071-9f69-c879103dd8af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.m_nav > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='findMenu']/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>220e66cc-44bd-4fb7-afec-1f5da688c92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Content/portal/absensi.png</value>
      <webElementGuid>5a8611e2-de78-43be-845d-51fd3d63894d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>8dc73871-da0a-46f8-ab76-92fc27f1998c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>6a804f81-ed0d-49d0-a9aa-9c92cd7a1cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>dbcfc764-04db-4179-9bf9-388edba84512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;findMenu&quot;)/div[@class=&quot;m_nav&quot;]/a[1]/img[1]</value>
      <webElementGuid>0d1fee57-66fb-43c5-92bf-d38ab4e0eaf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='findMenu']/div/a/img</value>
      <webElementGuid>38b7c106-cd84-45dc-8b7e-c04563991fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/img</value>
      <webElementGuid>f13d41de-e245-432d-b121-d3aeba6550e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Content/portal/absensi.png']</value>
      <webElementGuid>151522f3-1142-420f-9dfb-4934e3599046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
