<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hadir_karena</name>
   <tag></tag>
   <elementGuidId>20645329-630c-4997-9ed3-d3ad24bdda77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > #BecauseOf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/input[@id=&quot;BecauseOf&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AbsensiForm div >> internal:has-text=&quot;Lainnya&quot;i >> #BecauseOf</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>456fea2a-953c-424a-b1c4-311340838cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BecauseOf</value>
      <webElementGuid>33d90db7-5d22-40b4-918c-cc61c148257e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BecauseOf</value>
      <webElementGuid>e5e6488c-dbb8-434f-b801-0b2f5bca6b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f5223ac7-5229-4ca4-a30c-5e4f1e8b78bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Lainnya</value>
      <webElementGuid>9205aaed-b363-48b6-92d8-45d860733688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AbsensiForm&quot;)/table[@class=&quot;formTable&quot;]/tbody[1]/tr[7]/td[@class=&quot;valueColumn&quot;]/div[2]/input[@id=&quot;BecauseOf&quot;]</value>
      <webElementGuid>039558ae-6ada-4b87-95bc-0323f9f1c536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='BecauseOf'])[2]</value>
      <webElementGuid>87f7e89c-e9d7-47da-9370-96dc8fea95e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AbsensiForm']/table/tbody/tr[7]/td[2]/div[2]/input</value>
      <webElementGuid>59d6c888-7072-495d-89d3-6d5387a14e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0f2d724c-99b9-427b-9920-6b3f8edabfb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BecauseOf' and @name = 'BecauseOf' and @type = 'radio']</value>
      <webElementGuid>d276acbb-613e-4254-bb90-f1af0a9fbf06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
