<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>absensi_hadir</name>
   <tag></tag>
   <elementGuidId>4685df36-d59d-48aa-b935-bd5643b7f047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='PanelBar']/li[3]/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.k-link.k-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hadir&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7e24340-a158-4e2e-aa2f-342490e30aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-state-hover</value>
      <webElementGuid>28bfa3cd-954d-4124-9c23-d0feabb94220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Absensi/Form/Hadir</value>
      <webElementGuid>57eb1366-9bd9-4786-b035-109680e8a1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hadir </value>
      <webElementGuid>d73b376f-ba6a-41c3-ac81-173da01e0d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PanelBar&quot;)/li[@class=&quot;k-state-active k-item&quot;]/ul[@class=&quot;k-group k-panel&quot;]/li[@class=&quot;k-state-active k-item&quot;]/a[@class=&quot;k-link k-state-hover&quot;]</value>
      <webElementGuid>f953e6f4-5d84-42b4-8a0a-3ac45bbdbf35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='PanelBar']/li[3]/ul/li[4]/a</value>
      <webElementGuid>a39fe67c-a7ae-46af-a096-471a2cd8657c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hadir')]</value>
      <webElementGuid>3a84ce7e-ad70-4a72-822e-3422aa804b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketidakhadiran'])[1]/following::a[1]</value>
      <webElementGuid>b25116f8-f829-44f7-9461-9e4bf325d0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terlambat'])[1]/following::a[2]</value>
      <webElementGuid>eb7682ac-069e-4641-a9ee-5e97f20e2db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amnesti Absen'])[1]/preceding::a[1]</value>
      <webElementGuid>ca639468-4d72-423a-acf8-efa1a5b9d08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hadir']/parent::*</value>
      <webElementGuid>5010dfaf-4a46-4fee-80c4-4638a90178a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Absensi/Form/Hadir')]</value>
      <webElementGuid>3391756e-a76b-40b7-a51b-32abea42d854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[4]/a</value>
      <webElementGuid>a2f1cef4-ff53-4c18-87b0-418eec7647db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Absensi/Form/Hadir' and (text() = 'Hadir ' or . = 'Hadir ')]</value>
      <webElementGuid>55514a68-b15d-4bf4-be95-048d2d805dcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
