<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in with your organizational acco_ff227e (1)</name>
   <tag></tag>
   <elementGuidId>dabf3ce8-3a78-4459-b5be-0c7601a5bcc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SubmitButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SubmitButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da10850a-341a-4ae3-9685-54908cc71c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmitButton</value>
      <webElementGuid>742c1e4b-40e6-425a-8d1b-29055f6f24c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button</value>
      <webElementGuid>8a062a5c-308e-4fab-825e-c8e6f0c70c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d3a843e3-a62e-450d-aa67-c867da6f3fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>7386de98-eb42-4b8d-a55f-ae3d49c77db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmitButton&quot;)</value>
      <webElementGuid>4e2016fb-4828-4efe-acbb-5d8b9b2306af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SubmitButton']</value>
      <webElementGuid>c84181ba-e850-467e-9d09-097cbc603df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='BackgroundContainer']/tbody/tr[5]/td/input</value>
      <webElementGuid>456bd28f-3df4-419a-99d2-a9a46fa432e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/input</value>
      <webElementGuid>9cebbc66-ab68-414b-82e2-d66c81c1e766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SubmitButton' and @type = 'submit']</value>
      <webElementGuid>ebb1633f-27be-4aa6-993d-d0bf5fc8a2bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
